# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSTransformerEncoderCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  nhead: 8
  dim_feedfoward: 512
  num_layers: 6

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
